version: "3"
services:
  cors-anywhere:
    image: redocly/cors-anywhere:latest
    ports:
      - 49170:80
  webserver-storage:
    container_name: webserver-storage
    build:
      context: docker/webserver-storage/
    ports:
      - 49160:80
    restart: unless-stopped
