version: "3"
services:
  scd-registry-http-storage:
    container_name: scd-registry-http-storage
    build:
      context: .
      dockerfile: docker/scd-registry-http-storage/Dockerfile
    ports:
      - 49160:49160
    restart: unless-stopped
