version: "3"
services:
  webserver-storage:
    container_name: webserver-storage
    build:
      context: .
      dockerfile: docker/webserver-storage/Dockerfile
    ports:
      - 49160:49160
    restart: unless-stopped
