name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build-and-start-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start container stack
        run: docker-compose up -d
